name: Fetch and Deploy Code

on:
  push:
    branches:
      - main

jobs:
  fetch-and-restart:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Install SSH client
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    # Setup SSH keys
    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/bsr
        chmod 600 ~/.ssh/bsr
        ssh-keyscan -H 172.17.0.1 >> ~/.ssh/known_hosts

    # Test SSH connection
    - name: Test SSH connection
      run: |
        ssh -i ~/.ssh/bsr -o StrictHostKeyChecking=no baseerx@172.17.0.1 'echo "SSH connection successful!"'

    # Fetch the code to a different directory on the local Ubuntu system
    - name: Fetch code to custom directory
      run: |
        ssh -i ~/.ssh/bsr -o StrictHostKeyChecking=no baseerx@172.17.0.1 'mkdir -p /home/flask-gitactions && rm -rf /home/flask-gitactions/*'
        scp -i ~/.ssh/bsr -r $GITHUB_WORKSPACE/* baseerx@172.17.0.1:/home/flask-gitactions

    # Restart Nginx after fetching the code
    - name: Restart Nginx
      run: |
        ssh -i ~/.ssh/bsr -o StrictHostKeyChecking=no baseerx@172.17.0.1 'sudo systemctl restart nginx'

