name: SSH Connection Test

on:
  push:
    branches:
      - main

jobs:
  check-ssh-connection:
    runs-on: ubuntu-latest

    steps:
    # Install SSH client
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    # Setup SSH keys
    - name: Setup SSH keys
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 172.17.0.1 >> ~/.ssh/known_hosts

    # Test SSH connection
    - name: Test SSH connection
      run: |
        if ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no baseerx@172.17.0.1 'echo "SSH connection successful!"'; then
          echo "SSH connection test passed."
        else
          echo "SSH connection test failed."
          exit 1
        fi

